# Generated by Django 4.2.1 on 2023-06-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DroitUtilisateur',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
