# Generated by Django 4.2.1 on 2023-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_enfant_client', models.IntegerField(blank=True, null=True)),
                ('id_csp', models.IntegerField(blank=True, null=True)),
                ('id_collecte', models.IntegerField(blank=True, null=True)),
                ('total_achat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Achat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_numero_client', models.IntegerField()),
                ('prenom_client', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_client', models.CharField(blank=True, max_length=255, null=True)),
                ('date_achat_client', models.DateTimeField(primary_key=True, serialize=False)),
                ('nombre_enfant_client', models.IntegerField(blank=True, null=True)),
                ('id_categorie', models.IntegerField(blank=True, null=True)),
                ('id_collecte', models.CharField(blank=True, max_length=255, null=True)),
                ('id_numero_magasin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id_collecte', models.IntegerField(primary_key=True, serialize=False)),
                ('date_achat_client', models.DateTimeField(blank=True, null=True)),
                ('id_numero_magasin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Collecte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollecteProduit',
            fields=[
                ('id_collecte', models.IntegerField(primary_key=True, serialize=False)),
                ('id_produit', models.IntegerField()),
                ('quantite_produit', models.IntegerField()),
                ('prix_unitaire_produit', models.FloatField()),
            ],
            options={
                'db_table': 'Collecte_produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Csp',
            fields=[
                ('id_categorie', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CSP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DroitUtilisateur',
            fields=[
                ('id_droit_utilisateur', models.IntegerField(primary_key=True, serialize=False)),
                ('role_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('groupe_utilisateur', models.IntegerField(blank=True, null=True)),
                ('description_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Droit_utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id_numero_magasin', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_magasin', models.CharField(blank=True, max_length=255, null=True)),
                ('ville_magasin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Magasin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_numero_service', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(blank=True, max_length=255, null=True)),
                ('type_salarie', models.CharField(blank=True, max_length=255, null=True)),
                ('id_droit_utilisateur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_numero_utilisateur', models.IntegerField(primary_key=True, serialize=False)),
                ('mail_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_passe_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('type_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
                ('role_utilisateur', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': False,
            },
        ),
    ]
